lst=[10, 20, 30]
print(lst)
print()
print("--List Functions--")
print()
lst.append(40)
print("Adds element at end:",lst)
lst.clear()
print("Removes all elements:",lst)
lst= [10, 20, 30]
print("Creates copy of list:",lst.copy())
print("Counts occurrences:",lst.count(20))
lst.extend([40, 50])
print("Adds multiple elements:",lst)
print("Returns index position:",lst.index(20))
lst.insert(1, 15)
print("Inserts at position:",lst)
lst.pop()
print("Removes last element:",lst)
lst.remove(20)
print("Removes specific element:",lst)
lst.reverse()
print("Reverses list:",lst)
lst.sort()
print("Sorts list:",lst)
